package io.github.robertomike.hefesto.hefesto.models;

import io.github.robertomike.hefesto.enums.Status;
import jakarta.persistence.metamodel.ListAttribute;
import jakarta.persistence.metamodel.SetAttribute;
import jakarta.persistence.metamodel.SingularAttribute;
import jakarta.persistence.metamodel.StaticMetamodel;

/**
 * JPA Static Metamodel for User entity.
 * This class is manually created for testing type-safe queries.
 * In production, this should be auto-generated by the JPA annotation processor.
 */
@StaticMetamodel(User.class)
public class User_ {
    public static volatile SingularAttribute<User, Long> id;
    public static volatile SingularAttribute<User, String> name;
    public static volatile SingularAttribute<User, String> email;
    public static volatile SingularAttribute<User, String> photo;
    public static volatile SetAttribute<User, Status> status;
    public static volatile SetAttribute<User, Pet> pets;
    public static volatile ListAttribute<User, Address> addresses;
}
