# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: HefestoSql

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'hefesto'
          mysql root password: 1234

      - name: Test all the project
        run: |
          gradle :test :hibernate:test